"""
Ejercicio 7:

Un vendedor recibe un sueldo base más un 10% extra por comisión de sus ventas, el vendedor desea saber
cuánto dinero obtendrá por concepto de comisiones por las tres ventas que realiza en el mes y el total que
recibirá en el mes tomando en cuenta su sueldo base y comisiones.
"""

# Salary

SALARY = 350


def calculate_commission(sales_total: float) -> float:
    return sales_total * 0.10


def calculate_salary(sales_commision: float) -> float:
    return sales_commision + SALARY


def calculate_total_salary() -> None:

    # Getting sales information

    first_sale = float(input("Enter the first sale total: "))
    second_sale = float(input("Enter the second sale total: "))
    third_sale = float(input("Enter the third sale total: "))

    sales_total = first_sale + second_sale + third_sale

    # Calculate commision (10% of sales)

    commision = calculate_commission(sales_total)

    # Calculate salary

    salary_total = round(calculate_salary(commision), 2)
    print(f"\nThe commission generated by the 3 sales is: {commision}, and the total salary is: {salary_total}")


if __name__ == '__main__':
    calculate_total_salary()
